"""
ScribeTeX PDF Compilation
Wrapper for pdflatex to compile .tex files to PDF.
"""
import os
import subprocess
import logging

logger = logging.getLogger(__name__)


class LatexCompilationError(Exception):
    """Raised when LaTeX compilation fails."""
    
    def __init__(self, message: str, log_content: str = ""):
        super().__init__(message)
        self.log_content = log_content


def compile_tex_to_pdf(tex_file_path: str, output_dir: str) -> str:
    """
    Compile a .tex file to PDF using pdflatex.
    
    Args:
        tex_file_path: Absolute path to the .tex file
        output_dir: Directory for output files
        
    Returns:
        Absolute path to the generated PDF
        
    Raises:
        FileNotFoundError: If the source file doesn't exist
        RuntimeError: If pdflatex is not installed
        LatexCompilationError: If compilation fails
    """
    if not os.path.isfile(tex_file_path):
        raise FileNotFoundError(f"LaTeX source file not found: {tex_file_path}")

    os.makedirs(output_dir, exist_ok=True)
    tex_filename = os.path.basename(tex_file_path)
    base_name = os.path.splitext(tex_filename)[0]

    cmd = [
        "pdflatex",
        "-interaction=nonstopmode",
        "-output-directory", output_dir,
        tex_file_path
    ]

    # Run pdflatex twice to resolve references
    for run_number in range(2):
        try:
            process = subprocess.run(
                cmd,
                cwd=os.path.dirname(tex_file_path),
                capture_output=True,
                text=True,
                check=False,
                timeout=120  # 2 minute timeout per run
            )
            
            if process.returncode != 0:
                log_path = os.path.join(output_dir, f"{base_name}.log")
                log_content = "pdflatex log file not found."
                
                if os.path.exists(log_path):
                    with open(log_path, 'r', errors='ignore') as f:
                        log_content = f.read()
                
                raise LatexCompilationError(
                    f"LaTeX compilation failed on run {run_number + 1}.",
                    log_content=log_content
                )
                
        except FileNotFoundError:
            raise RuntimeError(
                "pdflatex command not found. "
                "Ensure a LaTeX distribution (e.g., TeX Live, MiKTeX) is installed "
                "and pdflatex is in your system PATH."
            )
        except subprocess.TimeoutExpired:
            raise LatexCompilationError(
                f"LaTeX compilation timed out on run {run_number + 1}."
            )

    pdf_path = os.path.join(output_dir, f"{base_name}.pdf")
    
    if not os.path.exists(pdf_path):
        raise FileNotFoundError(f"PDF file was not generated at {pdf_path}.")

    logger.info(f"PDF compiled successfully: {pdf_path}")
    return pdf_path


def cleanup_latex_aux_files(output_dir: str, base_name: str):
    """Remove auxiliary files generated by pdflatex."""
    aux_extensions = ['.aux', '.log', '.out', '.toc', '.lof', '.lot', '.bbl', '.blg']
    
    for ext in aux_extensions:
        aux_file = os.path.join(output_dir, f"{base_name}{ext}")
        if os.path.exists(aux_file):
            try:
                os.remove(aux_file)
            except OSError:
                pass
